// Emacs style mode select   -*- C++ -*- 
//-----------------------------------------------------------------------------
//
// $Id:$
//
// Copyright (C) 1993-1996 by id Software, Inc.
//
// This source is available for distribution and/or modification
// only under the terms of the DOOM Source Code License as
// published by id Software. All rights reserved.
//
// The source is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// FITNESS FOR A PARTICULAR PURPOSE. See the DOOM Source Code License
// for more details.
//
// $Log:$
//
// DESCRIPTION:
//	DOOM main program (D_DoomMain) and game loop (D_DoomLoop),
//	plus functions to determine game mode (shareware, registered),
//	parse command line parameters, configure game parameters (turbo),
//	and call the startup functions.
//
//-----------------------------------------------------------------------------


static const char rcsid[] = "$Id: d_main.c,v 1.8 1997/02/03 22:45:09 b1 Exp $";

#define	BGCOLOR		7
#define	FGCOLOR		8


#ifdef NORMALUNIX
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#endif


#include "doomdef.h"
#include "doomstat.h"

#include "dstrings.h"
#include "sounds.h"


#include "z_zone.h"
#include "w_wad.h"
#include "s_sound.h"
#include "v_video.h"

#include "f_finale.h"
#include "f_wipe.h"

#include "m_argv.h"
#include "m_misc.h"
#include "m_menu.h"

#include "i_system.h"
#include "i_sound.h"
#include "i_video.h"

#include "g_game.h"

#include "hu_stuff.h"
#include "wi_stuff.h"
#include "st_stuff.h"
#include "am_map.h"

#include "p_setup.h"
#include "r_local.h"


#include "d_main.h"

//
// D-DoomLoop()
// Not a globally visible function,
//  just included for source reference,
//  called by D_DoomMain, never exits.
// Manages timing and IO,
//  calls all ?_Responder, ?_Ticker, and ?_Drawer,
//  calls I_GetTime, I_StartFrame, and I_StartTic
//
void D_DoomLoop (void);


char*		wadfiles[MAXWADFILES];


boolean		devparm;	// started game with -devparm
boolean         nomonsters;	// checkparm of -nomonsters
boolean         respawnparm;	// checkparm of -respawn
boolean         fastparm;	// checkparm of -fast

boolean         drone;

boolean		singletics = false; // debug flag to cancel adaptiveness

/* SE/30 performance opt flags — enabled via doom.cfg (default OFF).
 * halfline    : render only even framebuffer rows (50% fewer pixel writes, visible scanlines)
 * affinetex   : linear-interpolate texture column per wall (saves ~80 cycles/col)
 * solidfloor  : fill floor/ceiling with solid colour (skip per-pixel texture mapping) */
int opt_halfline      = 0;
int opt_affine_texcol = 0;
int opt_solidfloor    = 0;
int opt_directfb      = 0;   /* 1 = skip double-buffer, render direct to screen */
/* Gray fill level for solid floor/ceiling: 0=white 1=25% 2=50% 3=~88% 4=black */
int solidfloor_gray   = 0;
/* Distance fog threshold (fixed_t scale units; 0=off).
 * Wall/sprite columns with rw_scale/xscale < fog_scale are skipped —
 * the solidfloor background shows through, creating a free fog effect.
 * Step size is 2048 per keypress (` to raise, \ to lower). */
int fog_scale         = 0;
/* 2× pixel-scale mode: render view at half resolution (QUAD blocks=8 → 256×128),
 * expand 2× in blit to fill 512px Mac screen width exactly.
 * Status bar displayed 1× centered (320px, 96px black bars each side).
 * Enabled by scale2x=1 in doom.cfg or -scale2x command line. Default OFF.
 * Max effective screenblocks is capped at 8 in this mode. */
int opt_scale2x       = 0;
/* Sound effects: 0=off (silent, zero overhead), 1=on (Sound Manager SFX).
 * Default OFF to preserve existing performance baseline. */
int opt_sound         = 0;
/* Monster AI throttle: skip P_Move for monsters farther than this (map units).
 * 1024 ≈ 1.2s walking distance.  0 = no throttle.  Tunable in options GUI. */
int monster_throttle_dist = 1024;

extern int detailLevel;   /* defined in m_menu.c */


//extern int soundVolume;
//extern  int	sfxVolume;
//extern  int	musicVolume;

extern  boolean	inhelpscreens;

skill_t		startskill;
int             startepisode;
int		startmap;
boolean		autostart;

FILE*		debugfile;

boolean		advancedemo;




char		wadfile[1024];		// primary wad file
char		mapdir[1024];           // directory of development maps
char		basedefault[1024];      // default file


void D_CheckNetGame (void);
void D_ProcessEvents (void);
void G_BuildTiccmd (ticcmd_t* cmd);
void D_DoAdvanceDemo (void);


//
// EVENT HANDLING
//
// Events are asynchronous inputs generally generated by the game user.
// Events can be discarded if no responder claims them
//
event_t         events[MAXEVENTS];
int             eventhead;
int 		eventtail;


//
// D_PostEvent
// Called by the I/O functions when input is detected
//
void D_PostEvent (event_t* ev)
{
    events[eventhead] = *ev;
    eventhead = (++eventhead)&(MAXEVENTS-1);
}


//
// D_ProcessEvents
// Send all the events of the given timestamp down the responder chain
//
void D_ProcessEvents (void)
{
    event_t*	ev;
	
    // IF STORE DEMO, DO NOT ACCEPT INPUT
    if ( ( gamemode == commercial )
	 && (W_CheckNumForName("map01")<0) )
      return;
	
    for ( ; eventtail != eventhead ; eventtail = (++eventtail)&(MAXEVENTS-1) )
    {
	ev = &events[eventtail];
	if (M_Responder (ev))
	    continue;               // menu ate the event
	G_Responder (ev);
    }
}




//
// D_Display
//  draw current display, possibly wiping it from the previous
//

// wipegamestate can be set to -1 to force a wipe on the next draw
gamestate_t     wipegamestate = GS_DEMOSCREEN;
extern  boolean setsizeneeded;
extern  int             showMessages;
void R_ExecuteSetViewSize (void);

/* Profiling accumulators (Mac 60Hz ticks), reset every 35 game tics.
 *   logic  = TryRunTics (game simulation + AI)
 *   render = R_RenderPlayerView total
 *   blit   = I_FinishUpdate (screens[0] → 1-bit framebuffer)
 *   sound  = S_UpdateSounds + I_UpdateSound + I_SubmitSound
 *   disp   = D_Display total; (disp - render - blit) = HUD/ST/border
 * 60 ticks = 1 real second, so values read directly as % of wall clock.
 * Render sub-profile exported from r_main.c: */
extern long prof_r_setup, prof_r_bsp, prof_r_planes, prof_r_masked;
extern long prof_r_segs, prof_r_seg_loop;   /* r_segs.c: seg count + segloop time */
extern long prof_r_segs_fogged;             /* r_segs.c: segs fully fog-culled (clip-only path) */
extern long prof_r_bbox_fog;               /* r_bsp.c:  BSP subtrees pruned by fog distance */
extern long prof_r_bbox_calls;             /* r_bsp.c:  total R_CheckBBox calls */
extern long prof_r_bbox_solidsegs;         /* r_bsp.c:  calls reaching solidsegs scan */
extern long prof_r_pixels;                   /* r_draw.c: total pixels drawn */
extern long prof_r_scale;                    /* r_segs.c: time in inlined scale computation */
extern long prof_r_scale_skip;               /* r_segs.c: segs hitting short-seg fast path */
extern long prof_palette_skips;              /* i_video_mac.c: I_SetPalette no-op calls */
extern long prof_r_quad_calls;              /* r_draw.c: R_DrawColumnQuadLow_Mono calls */
extern long prof_gticker_ptick;             /* g_game.c: time in P_Ticker */
extern int  quad_dbg_done;                  /* r_draw.c: reset to re-arm debug log */
static long prof_logic  = 0;
static long prof_render = 0;
static long prof_blit   = 0;
static long prof_sound  = 0;
static long prof_disp   = 0;
static long prof_hud_st = 0;   /* ST_Drawer time */
static long prof_hud_hu = 0;   /* HU_Drawer time */
static long prof_hud_mn = 0;   /* M_Drawer time (menu active frames only) */

void D_Display (void)
{
    static  boolean		viewactivestate = false;
    static  boolean		menuactivestate = false;
    static  boolean		inhelpscreensstate = false;
    static  boolean		fullscreen = false;
    static  gamestate_t		oldgamestate = -1;
    static  int			borderdrawcount;
    int				nowtime;
    int				tics;
    int				wipestart;
    int				y;
    boolean			done;
    boolean			wipe;
    boolean			redrawsbar;

    if (nodrawers)
	return;                    // for comparative timing / profiling
		
    redrawsbar = false;
    
    // change the view size if needed
    if (setsizeneeded)
    {
	R_ExecuteSetViewSize ();
	oldgamestate = -1;                      // force background redraw
	borderdrawcount = 3;
    }

    // save the current screen if about to wipe
    if (gamestate != wipegamestate)
    {
	/* Debug: log every state transition that triggers a wipe.
	 * Helps trace the ghost-DOOM-logo bug (extra logo frames during
	 * demo slideshow transitions). */
	{ extern int demosequence;
	  doom_log("D_Display: wipe triggered gs=%d->wgs=%d demosequence=%d\r",
		   (int)gamestate, (int)wipegamestate, demosequence); }
	wipe = true;
	/* In 2x mode the view area cleared each frame is only 256×128 (the
	 * source buffer size), leaving columns 256-319 / rows 128-199 of
	 * screens[0] stale with title/intermission content.  Clear the whole
	 * buffer before capturing the wipe start frame so the melt begins
	 * from black, matching non-2x behaviour.  One-time cost at transitions
	 * only — zero impact on gameplay frame rate. */
	if (opt_scale2x)
	    memset(screens[0], 0, SCREENWIDTH * SCREENHEIGHT);
	wipe_StartScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);
    }
    else
	wipe = false;

    if (gamestate == GS_LEVEL && gametic)
	HU_Erase();
    
    // do buffered drawing
    switch (gamestate)
    {
      case GS_LEVEL:
	if (!gametic)
	    break;
	if (automapactive)
	    AM_Drawer ();
	if (wipe || (viewheight != 200 && fullscreen) )
	    redrawsbar = true;
	if (inhelpscreensstate && !inhelpscreens)
	    redrawsbar = true;              // just put away the help screen
	{ long _st = I_GetMacTick(); ST_Drawer (viewheight == 200, redrawsbar); prof_hud_st += I_GetMacTick() - _st; }
	fullscreen = viewheight == 200;
	break;

      case GS_INTERMISSION:
	WI_Drawer ();
	break;

      case GS_FINALE:
	F_Drawer ();
	break;

      case GS_DEMOSCREEN:
	D_PageDrawer ();
	break;
    }
    
    // draw buffered stuff to screen
    I_UpdateNoBlit ();
    
    // draw the view directly
    if (gamestate == GS_LEVEL && !automapactive && gametic)
    {
	long _rt = I_GetMacTick();
	R_RenderPlayerView (&players[displayplayer]);
	prof_render += I_GetMacTick() - _rt;
    }

    /* Clear HU overlay flag before HU_Drawer so I_FinishUpdate knows whether
     * any message text was drawn into the screens[0] view area this frame.
     * HU_Drawer (hu_stuff.c) sets it back to true if a message is visible. */
    { extern boolean hu_overlay_active; hu_overlay_active = false; }
    if (gamestate == GS_LEVEL && gametic)
	{ long _hu = I_GetMacTick(); HU_Drawer(); prof_hud_hu += I_GetMacTick() - _hu; }

    // clean up border stuff
    if (gamestate != oldgamestate && gamestate != GS_LEVEL)
	I_SetPalette (W_CacheLumpName ("PLAYPAL",PU_CACHE));

    // see if the border needs to be initially drawn
    // In 2x mode: viewwindowx=0/viewwindowy=0, so border corner patches would be
    // drawn at negative coordinates → "exceeds LFB" console spam.  The border
    // content in screens[0] is also never blitted in the 2x direct path, so skip.
    if (gamestate == GS_LEVEL && oldgamestate != GS_LEVEL && !opt_scale2x)
    {
	viewactivestate = false;        // view was not active
	R_FillBackScreen ();    // draw the pattern into the back screen
	{ extern int border_needs_blit; border_needs_blit = 1; }
    }

    // see if the border needs to be updated to the screen
    if (gamestate == GS_LEVEL && !automapactive && scaledviewwidth != 320 && !opt_scale2x)
    {
	if (menuactive || menuactivestate || !viewactivestate)
	    borderdrawcount = 3;
	if (borderdrawcount)
	{
	    R_DrawViewBorder ();    // erase old menu stuff
	    borderdrawcount--;
	    { extern int border_needs_blit; border_needs_blit = 1; }
	}

    }

    menuactivestate = menuactive;
    viewactivestate = viewactive;
    inhelpscreensstate = inhelpscreens;
    oldgamestate = wipegamestate = gamestate;
    
    // draw pause pic
    if (paused)
    {
	if (automapactive)
	    y = 4;
	else
	    y = viewwindowy+4;
	V_DrawPatchDirect(viewwindowx+(scaledviewwidth-68)/2,
			  y,0,W_CacheLumpName ("M_PAUSE", PU_CACHE));
    }


    // menus go directly to the screen
    /* Redirect M_Drawer to menu_overlay_buf only when the menu is actually
     * active.  Skipping the 64KB memset + M_Drawer call every frame when no
     * menu is open saves ~0.5-1 fps on the SE/30.
     * screens[1] is Doom's border tile cache — do NOT use it here.
     * I_FinishUpdate applies menu_overlay_buf as solid white over the full screen. */
    if (menuactive)
    {
	extern byte *menu_overlay_buf;
	byte *saved = screens[0];
	memset(menu_overlay_buf, 0, SCREENWIDTH * SCREENHEIGHT);
	screens[0] = menu_overlay_buf;
	{ long _mn = I_GetMacTick(); M_Drawer(); prof_hud_mn += I_GetMacTick() - _mn; }
	screens[0] = saved;
    }
    NetUpdate ();         // send out any new accumulation


    // normal update
    if (!wipe)
    {
	long _bt = I_GetMacTick();
	I_FinishUpdate ();              // page flip or blit buffer
	prof_blit += I_GetMacTick() - _bt;
	return;
    }
    
    // wipe update
    wipe_EndScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);

    wipestart = I_GetTime () - 1;

    /* Tell I_FinishUpdate to do a full blit during the wipe.
     * The direct 1-bit rendering path must be suppressed so that
     * wipe_ScreenWipe has exclusive control over screens[0]/framebuffer. */
    extern boolean wipe_in_progress;
    wipe_in_progress = true;

    do
    {
	do
	{
	    nowtime = I_GetTime ();
	    tics = nowtime - wipestart;
	} while (!tics);
	wipestart = nowtime;
	done = wipe_ScreenWipe(wipe_Melt
			       , 0, 0, SCREENWIDTH, SCREENHEIGHT, tics);
	I_UpdateNoBlit ();
	if (menuactive) { extern byte *menu_overlay_buf; byte *saved = screens[0]; memset(menu_overlay_buf, 0, SCREENWIDTH * SCREENHEIGHT); screens[0] = menu_overlay_buf; M_Drawer (); screens[0] = saved; }  // menu overlay
	I_FinishUpdate ();                      // page flip or blit buffer
    } while (!done);

    wipe_in_progress = false;
}



//
//  D_DoomLoop
//
extern  boolean         demorecording;

void D_DoomLoop (void)
{
    /* Frame timing: real wall-clock FPS using TickCount (60 Hz).
     * ft_wall_start is the TickCount at the start of each measurement window.
     * Window still fires every 35 game tics so timing data stays comparable. */
    int  ft_frames     = 0;
    int  ft_last_tic   = 0;
    long ft_wall_start = I_GetMacTick();

    if (demorecording)
	G_BeginRecording ();

    if (M_CheckParm ("-debugfile"))
    {
	char    filename[20];
	sprintf (filename,"debug%i.txt",consoleplayer);
	printf ("debug output to: %s\n",filename);
	debugfile = fopen (filename,"w");
    }

    I_InitGraphics ();

    while (1)
    {
	// frame syncronous IO operations
	I_StartFrame ();

	// process one or more tics
	/* --- game logic --- */
	{
	    long _t = I_GetMacTick();
	    if (singletics)
	    {
		I_StartTic ();
		D_ProcessEvents ();
		G_BuildTiccmd (&netcmds[consoleplayer][maketic%BACKUPTICS]);
		if (advancedemo)
		    D_DoAdvanceDemo ();
		M_Ticker ();
		G_Ticker ();
		gametic++;
		maketic++;
	    }
	    else
	    {
		TryRunTics (); // will run at least one tic
	    }
	    prof_logic += I_GetMacTick() - _t;
	}

	/* --- sound update --- */
	{
	    long _t = I_GetMacTick();
	    if (opt_sound) {
		S_UpdateSounds (players[consoleplayer].mo);
#ifndef SNDSERV
		I_UpdateSound();
#endif
#ifndef SNDINTR
		I_SubmitSound();
#endif
	    }
	    prof_sound += I_GetMacTick() - _t;
	}

	/* --- display --- */
	{
	    long _t = I_GetMacTick();
	    D_Display ();
	    prof_disp += I_GetMacTick() - _t;
	}

	ft_frames++;

	/* Log real wall-clock FPS every 35 game tics.
	 * elapsed = real 60Hz ticks in this window; realfps*10 avoids float.
	 * All component values are 60Hz ticks accumulated over the window.
	 * hud = D_Display minus render and blit (ST_Drawer, HU_Drawer, border). */
	if (gametic - ft_last_tic >= 35)
	{
	    long elapsed = I_GetMacTick() - ft_wall_start;
	    if (elapsed < 1) elapsed = 1;
	    /* realfps*10 = frames * 600 / elapsed  (avoids float, 1 decimal) */
	    long realfps10 = (long)ft_frames * 600L / elapsed;
	    doom_log("FPS:%ld.%ld (gtic:%d) logic=%ld render=%ld blit=%ld hud=%ld sound=%ld\r",
		     realfps10/10, realfps10%10,
		     ft_frames,
		     prof_logic, prof_render, prof_blit,
		     prof_disp - prof_render - prof_blit,
		     prof_sound);
	    doom_log("  logic: ptick=%ld\r", prof_gticker_ptick);
	    doom_log("  render: setup=%ld bsp=%ld planes=%ld masked=%ld\r",
		     prof_r_setup, prof_r_bsp, prof_r_planes, prof_r_masked);
	    { /* cy/px: approx column-renderer cycles per screen pixel (SE/30 = 16MHz/60Hz).
	       * Uses long long to avoid overflow on very slow hardware. */
	      long cy_px = prof_r_pixels > 0
		  ? (long)((long long)prof_r_seg_loop * 266667LL / prof_r_pixels)
		  : 0;
	      doom_log("    bsp: segs=%ld segloop=%ld trav=%ld px=%ld cy/px=%ld fog_seg=%ld bbox=%ld scale=%ld skip=%ld\r",
		       prof_r_segs, prof_r_seg_loop,
		       prof_r_bsp - prof_r_seg_loop,
		       prof_r_pixels, cy_px,
		       prof_r_segs_fogged, prof_r_bbox_fog, prof_r_scale, prof_r_scale_skip);
	      doom_log("    bbox: calls=%ld solid=%ld fog=%ld angle_rej=%ld\r",
		       prof_r_bbox_calls, prof_r_bbox_solidsegs, prof_r_bbox_fog,
		       prof_r_bbox_calls - prof_r_bbox_solidsegs - prof_r_bbox_fog);
	    }
	    doom_log("  hud: st=%ld hu=%ld menu=%ld\r",
		     prof_hud_st, prof_hud_hu, prof_hud_mn);
	    doom_log("  pal_skips=%ld quad_calls=%ld snd_cpu=%d\r",
		     prof_palette_skips, prof_r_quad_calls,
		     I_GetSoundCPULoad());
	    doom_log_flush();  /* force HFS commit so data survives a crash */

	    ft_frames       = 0;
	    ft_last_tic     = gametic;
	    ft_wall_start   = I_GetMacTick();
	    prof_logic      = 0;
	    prof_render     = 0;
	    prof_blit       = 0;
	    prof_sound      = 0;
	    prof_disp       = 0;
	    prof_r_setup    = 0;
	    prof_r_bsp      = 0;
	    prof_r_planes   = 0;
	    prof_r_masked   = 0;
	    prof_r_segs        = 0;
	    prof_r_seg_loop    = 0;
	    prof_r_segs_fogged = 0;
	    prof_r_bbox_fog       = 0;
	    prof_r_bbox_calls     = 0;
	    prof_r_bbox_solidsegs = 0;
	    prof_r_pixels      = 0;
	    prof_r_scale       = 0;
	    prof_r_scale_skip  = 0;
	    prof_palette_skips = 0;
	    prof_r_quad_calls  = 0;
	    prof_gticker_ptick = 0;
	    prof_hud_st        = 0;
	    prof_hud_hu        = 0;
	    prof_hud_mn        = 0;
	    quad_dbg_done       = 0;   /* re-arm first-call debug next window */
	}
    }
}



//
//  DEMO LOOP
//
int             demosequence;
int             pagetic;
char                    *pagename;


//
// D_PageTicker
// Handles timing for warped projection
//
void D_PageTicker (void)
{
    if (--pagetic < 0)
	D_AdvanceDemo ();
}



//
// D_PageDrawer
//
void D_PageDrawer (void)
{
    V_DrawPatch (0,0, 0, W_CacheLumpName(pagename, PU_CACHE));
}


//
// D_AdvanceDemo
// Called after each demo or intro demosequence finishes
//
void D_AdvanceDemo (void)
{
    advancedemo = true;
}


//
// This cycles through the demo sequences.
// FIXME - version dependend demo numbers?
//
 void D_DoAdvanceDemo (void)
{
    players[consoleplayer].playerstate = PST_LIVE;  // not reborn
    advancedemo = false;
    usergame = false;               // no save / end game here
    paused = false;
    gameaction = ga_nothing;

    if ( gamemode == retail )
      demosequence = (demosequence+1)%7;
    else
      demosequence = (demosequence+1)%6;

    doom_log("D_DoAdvanceDemo: demosequence=%d gamestate=%d\r",
	     demosequence, (int)gamestate);

    switch (demosequence)
    {
      case 0:
	if ( gamemode == commercial )
	    pagetic = 35 * 11;
	else
	    pagetic = 170;
	gamestate = GS_DEMOSCREEN;
	pagename = "TITLEPIC";
	if ( gamemode == commercial )
	  S_StartMusic(mus_dm2ttl);
	else
	  S_StartMusic (mus_intro);
	break;
      case 1:
	G_DeferedPlayDemo ("demo1");
	break;
      case 2:
	pagetic = 200;
	gamestate = GS_DEMOSCREEN;
	pagename = "CREDIT";
	break;
      case 3:
	G_DeferedPlayDemo ("demo2");
	break;
      case 4:
	gamestate = GS_DEMOSCREEN;
	if ( gamemode == commercial)
	{
	    pagetic = 35 * 11;
	    pagename = "TITLEPIC";
	    S_StartMusic(mus_dm2ttl);
	}
	else
	{
	    pagetic = 200;

	    if ( gamemode == retail )
	      pagename = "CREDIT";
	    else if (W_CheckNumForName("HELP2") >= 0)
	      pagename = "HELP2";
	    else if (W_CheckNumForName("HELP") >= 0)
	      pagename = "HELP";
	    else if (W_CheckNumForName("HELP1") >= 0)
	      pagename = "HELP1";
	    else
	      pagename = "TITLEPIC";
	}
	break;
      case 5:
	G_DeferedPlayDemo ("demo3");
	break;
        // THE DEFINITIVE DOOM Special Edition demo
      case 6:
	G_DeferedPlayDemo ("demo4");
	break;
    }
}



//
// D_StartTitle
//
void D_StartTitle (void)
{
    gameaction = ga_nothing;
    demosequence = -1;
    D_AdvanceDemo ();
}




//      print title for every printed line
char            title[128];



//
// D_AddFile
//
void D_AddFile (char *file)
{
    int     numwadfiles;
    char    *newfile;
	
    for (numwadfiles = 0 ; wadfiles[numwadfiles] ; numwadfiles++)
	;

    newfile = malloc (strlen(file)+1);
    strcpy (newfile, file);
	
    wadfiles[numwadfiles] = newfile;
}

//
// IdentifyVersion
// Checks availability of IWAD files by name,
// to determine whether registered/commercial features
// should be executed (notably loading PWAD's).
//
void IdentifyVersion (void)
{

    char*	doom1wad;
    char*	doomwad;
    char*	doomuwad;
    char*	doom2wad;

    char*	doom2fwad;
    char*	plutoniawad;
    char*	tntwad;

    doom_log("IV: entered\r");
#ifdef NORMALUNIX
    char *home;
    char *doomwaddir;
    doom_log("IV: calling getenv\r");
    doomwaddir = getenv("DOOMWADDIR");
    if (!doomwaddir)
	doomwaddir = ".";
    doom_log("IV: doomwaddir=%s\r", doomwaddir);

    // Commercial.
    doom2wad = malloc(strlen(doomwaddir)+1+9+1);
    sprintf(doom2wad, "%s/doom2.wad", doomwaddir);
    doom_log("IV: doom2wad=%s\r", doom2wad);

    // Retail.
    doomuwad = malloc(strlen(doomwaddir)+1+8+1);
    sprintf(doomuwad, "%s/doomu.wad", doomwaddir);

    // Registered.
    doomwad = malloc(strlen(doomwaddir)+1+8+1);
    sprintf(doomwad, "%s/doom.wad", doomwaddir);

    // Shareware.
    doom1wad = malloc(strlen(doomwaddir)+1+9+1);
    sprintf(doom1wad, "%s/doom1.wad", doomwaddir);
    doom_log("IV: doom1wad=%s\r", doom1wad);

     // Bug, dear Shawn.
    // Insufficient malloc, caused spurious realloc errors.
    plutoniawad = malloc(strlen(doomwaddir)+1+/*9*/12+1);
    sprintf(plutoniawad, "%s/plutonia.wad", doomwaddir);

    tntwad = malloc(strlen(doomwaddir)+1+9+1);
    sprintf(tntwad, "%s/tnt.wad", doomwaddir);

    // French stuff.
    doom2fwad = malloc(strlen(doomwaddir)+1+10+1);
    sprintf(doom2fwad, "%s/doom2f.wad", doomwaddir);

    doom_log("IV: all mallocs done\r");
    home = getenv("HOME");
    if (!home)
      strcpy(basedefault, "doom.cfg");  /* Mac: use current dir */
    else
      sprintf(basedefault, "%s/.doomrc", home);
    doom_log("IV: basedefault=%s\r", basedefault);
#endif
    doom_log("IV: before M_CheckParm\r");
    if (M_CheckParm ("-shdev"))
    {
	gamemode = shareware;
	devparm = true;
	D_AddFile (DEVDATA"doom1.wad");
	D_AddFile (DEVMAPS"data_se/texture1.lmp");
	D_AddFile (DEVMAPS"data_se/pnames.lmp");
	strcpy (basedefault,DEVDATA"default.cfg");
	return;
    }

    if (M_CheckParm ("-regdev"))
    {
	gamemode = registered;
	devparm = true;
	D_AddFile (DEVDATA"doom.wad");
	D_AddFile (DEVMAPS"data_se/texture1.lmp");
	D_AddFile (DEVMAPS"data_se/texture2.lmp");
	D_AddFile (DEVMAPS"data_se/pnames.lmp");
	strcpy (basedefault,DEVDATA"default.cfg");
	return;
    }

    if (M_CheckParm ("-comdev"))
    {
	gamemode = commercial;
	devparm = true;
	/* I don't bother
	if(plutonia)
	    D_AddFile (DEVDATA"plutonia.wad");
	else if(tnt)
	    D_AddFile (DEVDATA"tnt.wad");
	else*/
	    D_AddFile (DEVDATA"doom2.wad");
	    
	D_AddFile (DEVMAPS"cdata/texture1.lmp");
	D_AddFile (DEVMAPS"cdata/pnames.lmp");
	strcpy (basedefault,DEVDATA"default.cfg");
	return;
    }

    doom_log("IV: access doom2fwad\r");
    if ( !access (doom2fwad,R_OK) )
    {
	gamemode = commercial;
	language = french;
	printf("French version\n");
	D_AddFile (doom2fwad);
	return;
    }

    doom_log("IV: access doom2wad\r");
    if ( !access (doom2wad,R_OK) )
    {
	gamemode = commercial;
	D_AddFile (doom2wad);
	return;
    }

    doom_log("IV: access plutoniawad\r");
    if ( !access (plutoniawad, R_OK ) )
    {
      gamemode = commercial;
      D_AddFile (plutoniawad);
      return;
    }

    doom_log("IV: access tntwad\r");
    if ( !access ( tntwad, R_OK ) )
    {
      gamemode = commercial;
      D_AddFile (tntwad);
      return;
    }

    doom_log("IV: access doomuwad\r");
    if ( !access (doomuwad,R_OK) )
    {
      gamemode = retail;
      D_AddFile (doomuwad);
      return;
    }

    doom_log("IV: access doomwad\r");
    if ( !access (doomwad,R_OK) )
    {
      gamemode = registered;
      D_AddFile (doomwad);
      return;
    }

    doom_log("IV: access doom1wad\r");
    if ( !access (doom1wad,R_OK) )
    {
      gamemode = shareware;
      D_AddFile (doom1wad);
      return;
    }

    printf("Game mode indeterminate.\n");
    gamemode = indetermined;

    /* No WAD found — show message on bg_window and exit cleanly. */
    if (!wadfiles[0])
    {
        extern void I_NoWadAlert(void);
        I_NoWadAlert();
        I_Quit();
    }
}

//
// Find a Response File
//
void FindResponseFile (void)
{
    int             i;
#define MAXARGVS        100
	
    for (i = 1;i < myargc;i++)
	if (myargv[i][0] == '@')
	{
	    FILE *          handle;
	    int             size;
	    int             k;
	    int             index;
	    int             indexinfile;
	    char    *infile;
	    char    *file;
	    char    *moreargs[20];
	    char    *firstargv;
			
	    // READ THE RESPONSE FILE INTO MEMORY
	    handle = fopen (&myargv[i][1],"rb");
	    if (!handle)
	    {
		printf ("\nNo such response file!");
		exit(1);
	    }
	    printf("Found response file %s!\n",&myargv[i][1]);
	    fseek (handle,0,SEEK_END);
	    size = ftell(handle);
	    fseek (handle,0,SEEK_SET);
	    file = malloc (size);
	    fread (file,size,1,handle);
	    fclose (handle);
			
	    // KEEP ALL CMDLINE ARGS FOLLOWING @RESPONSEFILE ARG
	    for (index = 0,k = i+1; k < myargc; k++)
		moreargs[index++] = myargv[k];
			
	    firstargv = myargv[0];
	    myargv = malloc(sizeof(char *)*MAXARGVS);
	    memset(myargv,0,sizeof(char *)*MAXARGVS);
	    myargv[0] = firstargv;
			
	    infile = file;
	    indexinfile = k = 0;
	    indexinfile++;  // SKIP PAST ARGV[0] (KEEP IT)
	    do
	    {
		myargv[indexinfile++] = infile+k;
		while(k < size &&
		      ((*(infile+k)>= ' '+1) && (*(infile+k)<='z')))
		    k++;
		*(infile+k) = 0;
		while(k < size &&
		      ((*(infile+k)<= ' ') || (*(infile+k)>'z')))
		    k++;
	    } while(k < size);
			
	    for (k = 0;k < index;k++)
		myargv[indexinfile++] = moreargs[k];
	    myargc = indexinfile;
	
	    // DISPLAY ARGS
	    printf("%d command-line args:\n",myargc);
	    for (k=1;k<myargc;k++)
		printf("%s\n",myargv[k]);

	    break;
	}
}


//
// D_DoomMain
//
void D_DoomMain (void)
{
    int             p;
    char                    file[256];

    doom_log("D_DoomMain: start\r");
    FindResponseFile ();
    doom_log("D_DoomMain: FindResponseFile done\r");

    IdentifyVersion ();
    doom_log("D_DoomMain: IdentifyVersion done, gamemode=%d\r", (int)gamemode);

    setbuf (stdout, NULL);
    modifiedgame = false;

    nomonsters = M_CheckParm ("-nomonsters");
    respawnparm = M_CheckParm ("-respawn");
    fastparm = M_CheckParm ("-fast");
    devparm = M_CheckParm ("-devparm");
    if (M_CheckParm ("-halfline"))   opt_halfline      = 1;
    if (M_CheckParm ("-affinetex")) opt_affine_texcol = 1;
    if (M_CheckParm ("-scale2x"))   opt_scale2x       = 1;
    if (M_CheckParm ("-directfb"))  opt_directfb      = 1;
    if (M_CheckParm ("-sound"))    opt_sound         = 1;
    if (M_CheckParm ("-altdeath"))
	deathmatch = 2;
    else if (M_CheckParm ("-deathmatch"))
	deathmatch = 1;

    doom_log("D_DoomMain: entering switch(gamemode)\r");
    switch ( gamemode )
    {
      case retail:
	sprintf (title,
		 "                         "
		 "The Ultimate DOOM Startup v%i.%i"
		 "                           ",
		 VERSION/100,VERSION%100);
	break;
      case shareware:
	sprintf (title,
		 "                            "
		 "DOOM Shareware Startup v%i.%i"
		 "                           ",
		 VERSION/100,VERSION%100);
	break;
      case registered:
	sprintf (title,
		 "                            "
		 "DOOM Registered Startup v%i.%i"
		 "                           ",
		 VERSION/100,VERSION%100);
	break;
      case commercial:
	sprintf (title,
		 "                         "
		 "DOOM 2: Hell on Earth v%i.%i"
		 "                           ",
		 VERSION/100,VERSION%100);
	break;
/*FIXME
       case pack_plut:
	sprintf (title,
		 "                   "
		 "DOOM 2: Plutonia Experiment v%i.%i"
		 "                           ",
		 VERSION/100,VERSION%100);
	break;
      case pack_tnt:
	sprintf (title,
		 "                     "
		 "DOOM 2: TNT - Evilution v%i.%i"
		 "                           ",
		 VERSION/100,VERSION%100);
	break;
*/
      default:
	sprintf (title,
		 "                     "
		 "Public DOOM - v%i.%i"
		 "                           ",
		 VERSION/100,VERSION%100);
	break;
    }
    
    printf ("%s\n",title);

    if (devparm)
	printf(D_DEVSTR);
    
    if (M_CheckParm("-cdrom"))
    {
	printf(D_CDROM);
	mkdir("c:\\doomdata",0);
	strcpy (basedefault,"c:/doomdata/default.cfg");
    }	
    
    // turbo option
    if ( (p=M_CheckParm ("-turbo")) )
    {
	int     scale = 200;
	extern int forwardmove[2];
	extern int sidemove[2];
	
	if (p<myargc-1)
	    scale = atoi (myargv[p+1]);
	if (scale < 10)
	    scale = 10;
	if (scale > 400)
	    scale = 400;
	printf ("turbo scale: %i%%\n",scale);
	forwardmove[0] = forwardmove[0]*scale/100;
	forwardmove[1] = forwardmove[1]*scale/100;
	sidemove[0] = sidemove[0]*scale/100;
	sidemove[1] = sidemove[1]*scale/100;
    }
    
    // add any files specified on the command line with -file wadfile
    // to the wad list
    //
    // convenience hack to allow -wart e m to add a wad file
    // prepend a tilde to the filename so wadfile will be reloadable
    p = M_CheckParm ("-wart");
    if (p)
    {
	myargv[p][4] = 'p';     // big hack, change to -warp

	// Map name handling.
	switch (gamemode )
	{
	  case shareware:
	  case retail:
	  case registered:
	    sprintf (file,"~"DEVMAPS"E%cM%c.wad",
		     myargv[p+1][0], myargv[p+2][0]);
	    printf("Warping to Episode %s, Map %s.\n",
		   myargv[p+1],myargv[p+2]);
	    break;
	    
	  case commercial:
	  default:
	    p = atoi (myargv[p+1]);
	    if (p<10)
	      sprintf (file,"~"DEVMAPS"cdata/map0%i.wad", p);
	    else
	      sprintf (file,"~"DEVMAPS"cdata/map%i.wad", p);
	    break;
	}
	D_AddFile (file);
    }
	
    p = M_CheckParm ("-file");
    if (p)
    {
	// the parms after p are wadfile/lump names,
	// until end of parms or another - preceded parm
	modifiedgame = true;            // homebrew levels
	while (++p != myargc && myargv[p][0] != '-')
	    D_AddFile (myargv[p]);
    }

    p = M_CheckParm ("-playdemo");

    if (!p)
	p = M_CheckParm ("-timedemo");

    if (p && p < myargc-1)
    {
	sprintf (file,"%s.lmp", myargv[p+1]);
	D_AddFile (file);
	printf("Playing demo %s.lmp.\n",myargv[p+1]);
    }
    
    // get skill / episode / map from parms
    startskill = sk_medium;
    startepisode = 1;
    startmap = 1;
    autostart = false;

		
    p = M_CheckParm ("-skill");
    if (p && p < myargc-1)
    {
	startskill = myargv[p+1][0]-'1';
	autostart = true;
    }

    p = M_CheckParm ("-episode");
    if (p && p < myargc-1)
    {
	startepisode = myargv[p+1][0]-'0';
	startmap = 1;
	autostart = true;
    }
	
    p = M_CheckParm ("-timer");
    if (p && p < myargc-1 && deathmatch)
    {
	int     time;
	time = atoi(myargv[p+1]);
	printf("Levels will end after %d minute",time);
	if (time>1)
	    printf("s");
	printf(".\n");
    }

    p = M_CheckParm ("-avg");
    if (p && p < myargc-1 && deathmatch)
	printf("Austin Virtual Gaming: Levels will end after 20 minutes\n");

    p = M_CheckParm ("-warp");
    if (p && p < myargc-1)
    {
	if (gamemode == commercial)
	    startmap = atoi (myargv[p+1]);
	else
	{
	    startepisode = myargv[p+1][0]-'0';
	    startmap = myargv[p+2][0]-'0';
	}
	autostart = true;
    }
    
    // init subsystems
    doom_log("D_DoomMain: before V_Init\r");
    printf ("V_Init: allocate screens.\n");
    V_Init ();
    doom_log("D_DoomMain: V_Init done\r");

    printf ("M_LoadDefaults: Load system defaults.\n");
    doom_log ("CHKPT: entering M_LoadDefaults\n");
    M_LoadDefaults ();              // load before initing other systems
    doom_log ("CHKPT: M_LoadDefaults done\r");
    doom_log("D_DoomMain: opt_halfline=%d opt_affinetex=%d opt_solidfloor=%d solidfloor_gray=%d detailLevel=%d opt_scale2x=%d opt_directfb=%d opt_sound=%d monster_throttle=%d\r",
             opt_halfline, opt_affine_texcol, opt_solidfloor, solidfloor_gray, detailLevel, opt_scale2x, opt_directfb, opt_sound, monster_throttle_dist);

    printf ("Z_Init: Init zone memory allocation daemon. \n");
    doom_log ("CHKPT: entering Z_Init\n");
    Z_Init ();
    doom_log ("CHKPT: Z_Init done\n");

    printf ("W_Init: Init WADfiles.\n");
    doom_log ("CHKPT: entering W_Init\n");
    W_InitMultipleFiles (wadfiles);
    doom_log ("CHKPT: W_Init done\n");
    

    // Check for -file in shareware
    if (modifiedgame)
    {
	// These are the lumps that will be checked in IWAD,
	// if any one is not present, execution will be aborted.
	char name[23][8]=
	{
	    "e2m1","e2m2","e2m3","e2m4","e2m5","e2m6","e2m7","e2m8","e2m9",
	    "e3m1","e3m3","e3m3","e3m4","e3m5","e3m6","e3m7","e3m8","e3m9",
	    "dphoof","bfgga0","heada1","cybra1","spida1d1"
	};
	int i;
	
	if ( gamemode == shareware)
	    I_Error("\nYou cannot -file with the shareware "
		    "version. Register!");

	// Check for fake IWAD with right name,
	// but w/o all the lumps of the registered version. 
	if (gamemode == registered)
	    for (i = 0;i < 23; i++)
		if (W_CheckNumForName(name[i])<0)
		    I_Error("\nThis is not the registered version.");
    }
    
    // Iff additonal PWAD files are used, print modified banner
    if (modifiedgame)
    {
	/*m*/printf (
	    "===========================================================================\n"
	    "ATTENTION:  This version of DOOM has been modified.  If you would like to\n"
	    "get a copy of the original game, call 1-800-IDGAMES or see the readme file.\n"
	    "        You will not receive technical support for modified games.\n"
	    "                      press enter to continue\n"
	    "===========================================================================\n"
	    );
	getchar ();
    }
	

    // Check and print which version is executed.
    switch ( gamemode )
    {
      case shareware:
      case indetermined:
	printf (
	    "===========================================================================\n"
	    "                                Shareware!\n"
	    "===========================================================================\n"
	);
	break;
      case registered:
      case retail:
      case commercial:
	printf (
	    "===========================================================================\n"
	    "                 Commercial product - do not distribute!\n"
	    "         Please report software piracy to the SPA: 1-800-388-PIR8\n"
	    "===========================================================================\n"
	);
	break;
	
      default:
	// Ouch.
	break;
    }

    printf ("M_Init: Init miscellaneous info.\n");
    M_Init ();

    printf ("R_Init: Init DOOM refresh daemon - ");
    R_Init ();

    printf ("\nP_Init: Init Playloop state.\n");
    P_Init ();

    printf ("I_Init: Setting up machine state.\n");
    I_Init ();

    printf ("D_CheckNetGame: Checking network game status.\n");
    D_CheckNetGame ();

    printf ("S_Init: Setting up sound.\n");
    if (opt_sound)
        S_Init (snd_SfxVolume /* *8 */, snd_MusicVolume /* *8*/ );
    else
        I_InitSound();  /* no-op when opt_sound=0, but keeps shutdown symmetric */

    printf ("HU_Init: Setting up heads up display.\n");
    HU_Init ();

    printf ("ST_Init: Init status bar.\n");
    ST_Init ();

    // check for a driver that wants intermission stats
    p = M_CheckParm ("-statcopy");
    if (p && p<myargc-1)
    {
	// for statistics driver
	extern  void*	statcopy;                            

	statcopy = (void*)atoi(myargv[p+1]);
	printf ("External statistics registered.\n");
    }
    
    // start the apropriate game based on parms
    p = M_CheckParm ("-record");

    if (p && p < myargc-1)
    {
	G_RecordDemo (myargv[p+1]);
	autostart = true;
    }
	
    p = M_CheckParm ("-playdemo");
    if (p && p < myargc-1)
    {
	singledemo = true;              // quit after one demo
	G_DeferedPlayDemo (myargv[p+1]);
	D_DoomLoop ();  // never returns
    }
	
    p = M_CheckParm ("-timedemo");
    if (p && p < myargc-1)
    {
	G_TimeDemo (myargv[p+1]);
	D_DoomLoop ();  // never returns
    }
	
    p = M_CheckParm ("-loadgame");
    if (p && p < myargc-1)
    {
	if (M_CheckParm("-cdrom"))
	    sprintf(file, "c:\\doomdata\\"SAVEGAMENAME"%c.dsg",myargv[p+1][0]);
	else
	    sprintf(file, SAVEGAMENAME"%c.dsg",myargv[p+1][0]);
	G_LoadGame (file);
    }
	

    if ( gameaction != ga_loadgame )
    {
	if (autostart || netgame)
	    G_InitNew (startskill, startepisode, startmap);
	else
	    D_StartTitle ();                // start up intro loop

    }

    D_DoomLoop ();  // never returns
}
